apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 100.100.62.194
etcd:
  endpoints:
  - http://100.100.62.193:2379
networking:
  serviceSubnet: 172.22.0.0/16
  podSubnet: 10.100.0.0/16
featureGates:    # In Kubernetes 1.11, CoreDNS has graduated to General Availability (GA) and is installed by default.
  CoreDNS: false
