apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: debugger
  namespace: songhao
spec:
  selector:
    matchLabels:
      app: debugger
  replicas: 2
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debugger
        image: amouat/network-utils
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      imagePullSecrets:
      - name: songhao.qiniu
