apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: servicemesh-webhook
webhooks:
- name: servicemesh-webhook.qiniu.com
  rules:
  - apiGroups:
    - "extensions"
    apiVersions:
    - v1beta1
    resources:
    - ingresses
    - virtualservice
    - gateway
    operations:
    - CREATE
    - UPDATE
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: istio-system
      name: servicemesh-webhook
      path: /ingresses
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZTRENDQXpDZ0F3SUJBZ0lJYWpSYWZtMUxqSTR3RFFZSktvWklodmNOQVFFTUJRQXdRakVMTUFrR0ExVUUKQmhNQ1EwNHhGVEFUQmdOVkJBb1RERk5sY25acFkyVWdUV1Z6YURFY01Cb0dBMVVFQXhNVFkyRXVhWE4wYVc4dApjM2x6ZEdWdExuTjJZekFlRncweE9EQTVNVGt4TVRRMU5UVmFGdzB5T0RBNU1UWXhNVFExTlRWYU1FSXhDekFKCkJnTlZCQVlUQWtOT01SVXdFd1lEVlFRS0V3eFRaWEoyYVdObElFMWxjMmd4SERBYUJnTlZCQU1URTJOaExtbHoKZEdsdkxYTjVjM1JsYlM1emRtTXdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFEbQppTHBoaWYwZUFtZU11Zi9lZTRCZlgzakl6Um8xYU1RWUNHK245LzNiTUZGNDBHK3BlVE1IT1FWMVlxdHphdHVMCnkvcDJUR3VVYVNQZ3l1eG1Vc3B2VWx3RkpXTlVBRnVlN3pkeXlLZExjb3ErOFkzeFhIdm9IQ010cVRGamVkZlYKMFRWWGt3RWdkd0xlQk9oaDQ2QlJjM0lqbzc1NkgxRWo3eldiOFZxbnFkYnR1ei9pazdTczQzUzhKZUZ2ZmpqQgovR0krK2FUb25McjdCd0ZFamZTZkRqdFdRUyt6S3EwZkFQVDNXTUFqZCtsaHJWTUJVRi9YdFZwcGxjbjdYY3lHCjJuNE1XU0VHak52d2xyMlBOSUM4LzM1NmQ4ZnhRTEZnRXdNMzNDQWdHVVZRUEpscnJ3dGJRY0xWUTd5WVNEaW4KMnVHRmZmZDhrNkp5YU52d1AxdHE3Mkk1K2dnMEsvay9vUmJLd3ZtTzVOL2E2SUY1L09MRG1iK2Fqcmt4TnZqMQo1bTRvT3p3MU5LcXZydVN2R21HTmFFWjFtMUhRaEh2eWMxV2NRMnRPalpNdVRXMGNJdTBNV2lvRWpEbG0wY1prCmpsNWYxOXBtM1lKbmVPS0ZFSCt1MVZ5OG5ibXFaWlJ2UjU1eE0yOXIzMzdhV2VTZ2o0VG1WS2UxNjVGTC9MOWEKbU5TaFJsNWpobWlWaFlqcjcyNllJRmowU3QxTFVyYU95VHZpZTl6aW5CNjlLcUJKSDRhSmo2VXhVOWxJaVZSRQorREVOUzRMd1E3NUljVUROU0k2RjJ4ZzQwVzJUMUVpUzBtSmZSdUdHNWRPL3hoV28wMTh2a3Y3WkV6RkdPM01OCjFGdnVJdXVLRXI3Z21DYXRMcGRnRTlJbmZrMlBRVUtwS2VackV6ZUpwUUlEQVFBQm8wSXdRREFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUJCakFkQmdOVkhRNEVGZ1FVL25mS1l2bGV4eTA1UndpZworVmlyOXJZNk5oWXdEUVlKS29aSWh2Y05BUUVNQlFBRGdnSUJBSXdFMHRsRFk2VU9WNTI2bFowM3VaQm9STzdDCkhxRHFBSUlZd2RTV1U1blBJSzY4ZStVRzhGZHBrK2ZLWktjUlBoYWJBTi9TN1Z0bjY5OEg0TUlsZWhLN3kyM2wKMi90WmVSWHU5ODJOU21mcW5VcDhJRk80cjZhbDVjNzJVeDRyeDlxNW41Vy9haUlzaEZEbkIzMGY4VTVVZTFHUgpXbVJKUGo4OGFwZzJEU1lZb3J1MmZRT25zanEvbjE4SXByRnNRRDZDSnNzWHZTcER4dnEwNkQ2d05LV0dZa3NYCjBXM2doa1d0ZGxWU0FEc1kydHNxQUUyN0hsRlVPZGhUeDZKaTRJWlNzekhyQ1lIcGcwbVdKbjFQVFhIS0JjeG0KeHpGWWJSRGIwUGw2Y3VSQlpzbzVPUS9QUTZYNUpYanBnWjVaOUVyL2JZUTJDYTlqSXp0TndlNWN6UUhtUTU4WQp5Nk5GQ1FnV3JlcXJxM0Zyd1lnblhWRTQxcDUwSGZCT1lCZUhxOFBub09oaHo0c3pTMjBjZ2ZqR2ordkVPbE9LCm5pSlBKc0p6RmYzeGV0bldqbWQ0K0x1M1ZiY0t2WlFKU0hieTZQTlVZR0pxS2dmUjlzNXlpMysrSmxLY0FzYTQKNU1Ha2dOS1ZMLzN2QmVsVWJzRzdDaFlmOFpIc0R2VEhkcWRGNjZRTkNVaHMrd1FkSlY1bXgrdU1pMXZLenlpdwpmV0dsbXhidTlaTGZBbm5VcnJ1TUlVOXk5ODBRSjN1eDJJdGFQUDV3amNOWjVtUmxZNG0zV0doVHpmZWhCT1FZCkFZdUFpa3BzVElZL2dVZFRVMFpBNU9mVWJNdUFoVDdKbnJVUnhZLytMcWlWWjdEQTA4WkdZWFYvRmQ4YUhtc04KQ0ZtQnVHdFc1eFA2cHQzcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-system
  name: servicemesh-webhook
spec:
  type: ExternalName
  externalName: 172.31.64.60
