apiVersion: v1
kind: ServiceAccount
metadata:
  name: host-checker-service-account
  namespace: istio-system
  labels:
    app: host-checker
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: host-checker
  name: host-checker-istio-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: host-checker-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: host-checker-istio-system
subjects:
  - kind: ServiceAccount
    name: host-checker-service-account
    namespace: istio-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: host-checker
  namespace: istio-system
  labels:
    app: host-checker
spec:
  template:
    metadata:
      labels:
        app: host-checker
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: host-checker-service-account
      containers:
        - name: host-checker
          image: "reg.qiniu.com/exiaohao/host-checker:dev"
          imagePullPolicy: Always
          args:
          - --masterURL
          - https://10.7.0.194:6443
      imagePullSecrets:
      - name: qiniu
