apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 10.7.3.194
etcd:
  endpoints:
  - http://10.7.3.193:2379
networking:
  serviceSubnet: 172.21.0.0/16
  podSubnet: 10.98.0.0/16
