apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 172.20.0.51
etcd:
  endpoints:
  - http://172.31.0.201:2379
networking:
  serviceSubnet: 172.21.0.0/16
  podSubnet: 10.98.0.0/16
